// email-us/index.vue
<template>
  <ad-card id="email-us">
    <template #content>
      <form class="email-us-form" @submit.prevent="submitForm">
        <div v-for="field in fields" :key="field.id" class="form-group">
          <ad-label :label="field.label" :for="field.id" />
          <component
            :is="getComponent(field.component)"
            v-model="form[field.id]"
            :id="field.id"
            :type="field.type"
            :placeholder="field.placeholder"
            :invalid="!!errors[field.id]"
            :autocomplete="field.autocomplete"
            :options="field.options"
            :option-label="field.options ? 'label' : undefined"
            :option-value="field.options ? 'value' : undefined"
            ad-type="main"
          />
          <small v-if="errors[field.id]" class="error-message">
            {{ errors[field.id] }}
          </small>
        </div>

        <div
          class="form-group checkbox-group"
          v-tooltip.left="t('form-consent-tooltip')"
        >
          <ad-checkbox
            ad-type="main"
            inputId="consent"
            v-model="form.consent"
            :binary="true"
            :invalid="!!errors.consent"
          />
          <ad-label :label="$t('form-consent')" for="consent" />
          <small v-if="errors.consent" class="error-message"
            >{{ errors.consent }}</small
          >
        </div>

        <nuc-submit-button
          type="submit"
          variant="primary"
          :label="isSubmitting ? $t('form-sending') : $t('form-submit')"
          :disabled="isSubmitting"
        />
      </form>

      <div class="email-us-footer">
        <span class="response-text">{{ $t('form-response-text') }}</span>
        <span class="response-badge">{{ $t('form-response-badge') }}</span>
      </div>
    </template>
  </ad-card>
</template>

<script setup lang="ts">
import { navigateTo } from 'nuxt/app'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import {
  emailUsFormFieldKeys,
  getComponent,
  getEmailUsTextFields,
  submitContactForm,
} from 'nucleify'
import type {
  ContactFormDataInterface,
  ContactFormErrorsInterface,
} from 'nucleify'

const emit = defineEmits(['success'])
const { t, locale } = useI18n()

const fields = computed(() => getEmailUsTextFields(t))

const form = ref<ContactFormDataInterface>({
  email: '',
  website_type: '',
  consent: false,
})

const errors = ref<ContactFormErrorsInterface>({})
const isSubmitting = ref(false)

emailUsFormFieldKeys.forEach((field) => {
  watch(
    () => form.value[field],
    () => {
      if (errors.value[field]) errors.value[field] = undefined
    }
  )
})

async function submitForm(): Promise<void> {
  await submitContactForm({
    form,
    errors,
    isSubmitting,
    t,
    onSuccess: () => {
      emit('success')
      navigateTo(`/${locale.value}/thank-you`)
    },
  })
}
</script>

<style lang="scss">
@import 'index';
</style>

// email-us/index.tsx
'use client'

import {
  type ChangeEvent,
  type FormEvent,
  type JSX,
  useMemo,
  useState,
} from 'react'

import type {
  ContactFormDataInterface,
  ContactFormErrorsInterface,
  FormFieldInterface,
} from 'nucleify'
import {
  AdCard,
  AdCheckbox,
  AdInputText,
  AdLabel,
  AdSelect,
  getEmailUsTextFields,
  NucSubmitButton,
  submitContactForm,
  t,
} from 'nucleify'

import './_index.scss'

type NucSectionEmailUsProps = {
  onSuccess?: () => void
  cardClassName?: string
}

const initialForm: ContactFormDataInterface = {
  email: '',
  website_type: '',
  consent: false,
}

export function NucSectionEmailUs({
  onSuccess,
  cardClassName = '',
}: NucSectionEmailUsProps = {}): JSX.Element {
  const fields = useMemo(() => getEmailUsTextFields(t), [])
  const [form, setForm] = useState<ContactFormDataInterface>(initialForm)
  const [errors, setErrors] = useState<ContactFormErrorsInterface>({})
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [responseMessage, setResponseMessage] = useState('')

  const clearFieldError = (field: keyof ContactFormDataInterface): void => {
    if (!errors[field]) return
    setErrors((prev) => ({ ...prev, [field]: undefined }))
  }

  const handleFieldChange =
    (field: keyof Omit<ContactFormDataInterface, 'consent'>) =>
    (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>): void => {
      const value = event.target.value
      setForm((prev) => ({ ...prev, [field]: value }))
      clearFieldError(field)
    }

  const handleSelectChange =
    (field: keyof Omit<ContactFormDataInterface, 'consent'>) =>
    (event: { value: string }): void => {
      setForm((prev) => ({ ...prev, [field]: event.value || '' }))
      clearFieldError(field)
    }

  const handleConsentChange = (checked: boolean): void => {
    setForm((prev) => ({ ...prev, consent: checked }))
    clearFieldError('consent')
  }

  async function submitForm(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault()
    setIsSubmitting(true)
    setResponseMessage('')

    const result = await submitContactForm(form)

    if (!result.success) {
      setErrors(result.errors || {})
      if (result.message) setResponseMessage(result.message)
      setIsSubmitting(false)
      return
    }

    setErrors({})
    setForm(initialForm)
    setResponseMessage(result.message || '')
    onSuccess?.()
    setIsSubmitting(false)
  }

  const renderField = (field: FormFieldInterface): JSX.Element => {
    const commonProps = {
      nuiType: 'main',
      id: field.id,
      placeholder: field.placeholder,
      invalid: !!errors[field.id],
    }

    if (field.component === 'select') {
      return (
        <AdSelect
          {...commonProps}
          className="p-dropdown"
          options={field.options || []}
          optionLabel="label"
          optionValue="value"
          showClear={false}
          value={form[field.id]}
          onChange={handleSelectChange(field.id)}
        />
      )
    }

    return (
      <AdInputText
        {...commonProps}
        className="p-inputtext"
        type={field.type}
        autoComplete={field.autocomplete}
        value={form[field.id]}
        onChange={handleFieldChange(field.id)}
      />
    )
  }

  const cardClassNames = ['p-card', cardClassName].filter(Boolean).join(' ')

  return (
    <AdCard className={cardClassNames} id="email-us">
      <form className="email-us-form" onSubmit={submitForm}>
        {fields.map((field) => (
          <div className="form-group" key={field.id}>
            <AdLabel forInput={field.id} label={field.label} />
            {renderField(field)}
            {errors[field.id] && (
              <small className="error-message">{errors[field.id]}</small>
            )}
          </div>
        ))}

        <div className="form-group checkbox-group">
          <AdCheckbox
            nuiType="main"
            className="p-checkbox"
            checked={form.consent}
            inputId="consent"
            invalid={!!errors.consent}
            onChange={(event) => handleConsentChange(Boolean(event.checked))}
          />
          <AdLabel forInput="consent" label={t('form-consent')} />
          {errors.consent && (
            <small className="error-message">{errors.consent}</small>
          )}
        </div>

        <NucSubmitButton
          className="submit-button"
          disabled={isSubmitting}
          label={isSubmitting ? t('form-sending') : t('form-submit')}
          type="submit"
          variant="primary"
        />
      </form>

      <div className="email-us-footer">
        <span className="response-text">{t('form-response-text')}</span>
        <span className="response-badge">{t('form-response-badge')}</span>
      </div>

      {responseMessage && (
        <small className="error-message">{responseMessage}</small>
      )}
    </AdCard>
  )
}
