// email-us/dialog/index.vue
<template>
  <nuc-submit-button
    :class="props.buttonClass"
    :label="props.buttonLabel || $t('form-get-in-touch')"
    :icon="props.buttonIcon"
    variant="primary"
    @click="showDialog = true"
  />

  <client-only>
    <Dialog
      v-model:visible="showDialog"
      :modal="true"
      :dismissable-mask="true"
      :draggable="false"
      :pt="{
        pcCloseButton: {
          root: {
          'nui-type': 'main',
          }
        }
      }"
    >
      <nuc-section-email-us @success="handleEmailSuccess" />
    </Dialog>
  </client-only>
</template>

<script setup lang="ts">
import { ref } from 'vue'

import type { NucEmailUsDialogPropsInterface } from 'nucleify'

const props = withDefaults(defineProps<NucEmailUsDialogPropsInterface>(), {
  buttonLabel: '',
  buttonClass: '',
  buttonIcon: 'mdi:message-text-outline',
  buttonStrong: '',
})

const showDialog = ref(false)

function handleEmailSuccess(): void {
  showDialog.value = false
}
</script>

<style lang="scss">
@import 'index';
</style>

// email-us/dialog/index.tsx
'use client'

import { type JSX, type ReactNode, useState } from 'react'

import type { NucEmailUsDialogPropsInterface } from 'nucleify'
import { AdDialog, NucSectionEmailUs, NucSubmitButton, t } from 'nucleify'

const SECTION_EMAIL_DIALOG_CLASS = 'section-email-us-dialog'

const emailDialogClosePt = {
  closeButton: {
    root: { 'nui-type': 'main' as const },
  },
}

export interface NucEmailUsDialogFrameProps {
  visible: boolean
  onHide: () => void
  children: ReactNode
  dialogClassName?: string
  header?: ReactNode
}

export function NucEmailUsDialogFrame({
  visible,
  onHide,
  children,
  dialogClassName,
  header,
}: NucEmailUsDialogFrameProps): JSX.Element {
  const rootClassName =
    dialogClassName?.trim() + ' ' + SECTION_EMAIL_DIALOG_CLASS

  return (
    <AdDialog
      visible={visible}
      modal
      dismissableMask
      draggable={false}
      className={rootClassName}
      header={header}
      showHeader
      onHide={onHide}
      pt={emailDialogClosePt}
    >
      {children}
    </AdDialog>
  )
}

export function NucSectionEmailUsDialog({
  buttonLabel = '',
  buttonClass = '',
  buttonIcon = 'mdi:message-text-outline',
}: NucEmailUsDialogPropsInterface): JSX.Element {
  const [showDialog, setShowDialog] = useState(false)

  return (
    <>
      <NucSubmitButton
        className={buttonClass}
        icon={buttonIcon}
        label={buttonLabel || t('form-get-in-touch')}
        variant="primary"
        onClick={() => setShowDialog(true)}
      />

      <NucEmailUsDialogFrame
        visible={showDialog}
        onHide={() => setShowDialog(false)}
      >
        <NucSectionEmailUs
          onSuccess={() => setShowDialog(false)}
          cardClassName="p-card"
        />
      </NucEmailUsDialogFrame>
    </>
  )
}
