// footer/index.tsx
'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import type { JSX } from 'react'

import {
  AdAnchor,
  AdLogo,
  AdLogoSymbol,
  getActiveLocale,
  getColumns,
  t,
} from 'nucleify'

import './_index.scss'

function tWithParams(
  key: string,
  params: Record<string, string | number>
): string {
  let value = t(key)
  for (const [paramKey, paramValue] of Object.entries(params)) {
    value = value.replaceAll(`{{${paramKey}}}`, String(paramValue))
  }
  return value
}

function decodeLocaleEmail(value: string): string {
  return value.replace("{'@'}", '@')
}

export function NucSectionFooter(): JSX.Element {
  const pathname = usePathname() || ''
  const lang = getActiveLocale()
  const year = new Date().getFullYear()
  const devPrefix = pathname.includes('/dev') ? '/dev' : ''
  const columns = getColumns(lang, t, devPrefix)
  const logoSize = 72
  const companyLink =
    'https://aleo.com/pl/firma/atomic-it-spolka-z-ograniczona-odpowiedzialnoscia'
  const companyEmail = decodeLocaleEmail(t('footer-company-email'))

  return (
    <section id="footer">
      <div className="footer-content-container">
        <div className="top">
          <AdLogoSymbol dimensions={logoSize} />

          <div className="brand">
            <AdAnchor className="header" href="#start">
              <AdLogo dimensions={logoSize} nuiType="main" />
              <h1 className="name">Nucleify</h1>
            </AdAnchor>
          </div>

          <div className="columns">
            {columns.map((column, columnIndex) => (
              <div className="column" key={columnIndex}>
                {column.map((item, itemIndex) => (
                  <Link href={item.url} key={itemIndex}>
                    {item.header ? (
                      <p className="column-header">{item.name}</p>
                    ) : (
                      <span>{item.name}</span>
                    )}
                  </Link>
                ))}
              </div>
            ))}
          </div>
        </div>

        <div className="bottom">
          <div className="company-info">
            <a href={companyLink} rel="noreferrer" target="_blank">
              {t('footer-company-name')}
            </a>
            <span className="separator">|</span>
            <a href={companyLink} rel="noreferrer" target="_blank">
              {t('footer-company-nip')}
            </a>
            <span className="separator">|</span>
            <a href={companyLink} rel="noreferrer" target="_blank">
              {t('footer-company-address')}
            </a>
            <span className="separator">|</span>
            <a href={`mailto:${companyEmail}`}>{companyEmail}</a>
          </div>

          <span className="copyright">
            {tWithParams('footer-copyright', { year })}
          </span>
        </div>
      </div>
      <div className="hexagon-rows-container" />
    </section>
  )
}

// components/footer/index.vue
<template>
  <section id="footer">
    <nuc-grid-background />
    <div class="footer-cta">
      <ad-heading :tag="2" :text="t('footer-cta-heading')" class="cta-heading" />
      <p class="cta-subheading">{{ t('footer-cta-subheading') }}</p>
      <nuc-section-email-us-dialog />
    </div>

    <div class="footer-content-container">
      <div class="top">
        <div class="brand">
          <ad-anchor :href="`/${route.params.lang}/home#start`" class="header">
            <ad-logo :dimensions="isMobile() ? 36 : 48" ad-type="main" />
            <ad-heading :tag="3" text="Nucleify" class="name" />
          </ad-anchor>
        </div>

        <div class="columns">
          <div
            v-for="(column, columnIndex) in columns"
            :key="columnIndex"
            :class="`column`"
          >
            <nuxt-link
              v-for="(item, itemIndex) in column"
              :key="itemIndex"
              :to="item.url"
            >
              <ad-paragraph
                v-if="item?.header"
                class="column-header"
                :text="item.name"
              />
              <span v-else>{{ item.name }}</span>
            </nuxt-link>
          </div>
        </div>
      </div>

      <div class="bottom">
        <div class="company-info">
          <a :href="companyLink" target="_blank">
            {{ t('footer-company-name') }}
          </a>
          <span class="separator">|</span>
          <a :href="companyLink" target="_blank">
            {{ t('footer-company-nip') }}
          </a>
          <span class="separator">|</span>
          <a :href="companyLink" target="_blank">
            {{ t('footer-company-address') }}
          </a>
          <span class="separator">|</span>
          <a :href="`mailto:${t('footer-company-email')}`">
            {{ t('footer-company-email') }}
          </a>
        </div>
        <span class="copyright">
          {{ t('footer-copyright', { year }) }}
        </span>
      </div>
    </div>
    <nuc-animation-hexagons />
  </section>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import { isMobile } from 'nucleify'
import { getColumns } from './items'

const route = useRoute()
const { t } = useI18n()
const year = new Date().getFullYear()

const companyLink =
  'https://aleo.com/pl/firma/atomic-it-spolka-z-ograniczona-odpowiedzialnoscia'

const isDevContext = computed(() => route.path.includes('/dev'))

const columns = computed(() => {
  const lang = (route.params.lang as string) || 'en'
  return getColumns(lang, t, isDevContext.value ? '/dev' : '')
})
</script>
