// navbar/index.tsx
'use client'

import { usePathname } from 'next/navigation'
import type { JSX } from 'react'

import {
  AdAnchor,
  AdButton,
  AdLogo,
  DOC_CATEGORIES,
  NucDarkModeToggler,
  NucDocumentationNavbarNav,
  NucLangSwitcher,
  NucNavbarDrawer,
  NucNavbarLinks,
  NucSectionEmailUsDialog,
  useNavbar,
  useNavbarViewport,
} from 'nucleify'

import './_index.scss'

function getLangFromPathname(pathname: string): string {
  const [firstSegment] = pathname.split('/').filter(Boolean)
  return firstSegment || 'en'
}

function isDevDocsPath(pathname: string): boolean {
  return pathname.includes('/dev') || pathname.includes('/docs')
}

function isDocsPath(pathname: string): boolean {
  return pathname.includes('/docs')
}

export function NucSectionNavbar(): JSX.Element {
  const pathname = usePathname()
  const lang = getLangFromPathname(pathname)
  const isDevPage = isDevDocsPath(pathname)
  const isDocsPage = isDocsPath(pathname)
  const { navbarExpanded, toggleNavbar } = useNavbar('next')
  const { isDesktopNav } = useNavbarViewport({ docsLayout: isDocsPage })

  const navbarClassName = [
    'navbar',
    isDevPage ? 'navbar-dev' : '',
    isDocsPage ? 'navbar-docs' : '',
  ]
    .filter(Boolean)
    .join(' ')
  const homeHref = `/${lang}/${isDevPage ? 'dev' : 'home'}`

  const closeDrawer = (): void => {
    if (navbarExpanded) {
      toggleNavbar()
    }
  }

  return (
    <nav className={navbarClassName}>
      <div className="container">
        <AdAnchor
          aria-label="Home"
          className="application-header"
          href={homeHref}
        >
          <AdLogo adType="main" />
          {isDevPage ? (
            <h1 className="application-header-text">Nucleify</h1>
          ) : null}
        </AdAnchor>

        {isDocsPage ? (
          <div className="navbar-docs-nav">
            <NucDocumentationNavbarNav categories={DOC_CATEGORIES} />
          </div>
        ) : null}

        {isDevPage ? (
          <>
            {isDesktopNav ? (
              <div className="navbar-center">
                <NucNavbarLinks variant="text" />
              </div>
            ) : null}
            <div className="navbar-end">
              {isDesktopNav ? <NucNavbarLinks variant="actions" /> : null}
              <NucLangSwitcher />
              {!isDesktopNav ? (
                <AdButton
                  aria-label="Menu"
                  className="navbar-drawer-toggler"
                  icon={navbarExpanded ? undefined : 'prime:align-justify'}
                  onClick={toggleNavbar}
                />
              ) : null}
            </div>
          </>
        ) : (
          <div className="navbar-actions">
            <NucDarkModeToggler />
            <NucSectionEmailUsDialog />
          </div>
        )}
      </div>

      {isDevPage && !isDesktopNav ? (
        <NucNavbarDrawer onHide={closeDrawer} visible={navbarExpanded}>
          <NucNavbarLinks onCloseDrawer={closeDrawer} />
          <NucLangSwitcher />
        </NucNavbarDrawer>
      ) : null}
    </nav>
  )
}

// navbar/index.vue
<!--suppress HtmlUnknownAnchorTarget -->
<template>
  <nav
    class="navbar"
    :class="{ 'navbar-dev': isDevPage, 'navbar-docs': isDocsPage }"
  >
    <div class="container">
      <a
        class="application-header"
        :href="`/${lang}/${isDevPage ? 'dev' : 'home'}`"
        aria-label="Home"
      >
        <ad-logo ad-type="main" />

        <ad-heading
          v-if="isDevPage"
          :tag="1"
          text="Nucleify"
          class="application-header-text"
        />
      </a>

      <div v-if="isDocsPage" class="navbar-docs-nav">
        <nuc-documentation-navbar-nav :categories="DOC_CATEGORIES" />
      </div>

      <div v-if="isDevPage" class="navbar-center">
        <nuc-navbar-links variant="text" />
      </div>

      <div v-if="isDevPage" class="navbar-end">
        <nuc-navbar-links variant="actions" />
        <nuc-lang-switcher />
        <ad-button
          class="navbar-drawer-toggler"
          :icon="navbarExpanded ? 'hidden' : 'prime:align-justify'"
          aria-label="Menu"
          @click="toggleNavbar()"
        />
      </div>

      <div v-else class="navbar-actions">
        <nuc-dark-mode-toggler />
        <nuc-section-email-us-dialog />
      </div>
    </div>
    <nuc-navbar-drawer v-if="isDevPage" v-model:visible="navbarExpanded">
      <nuc-navbar-links @close-drawer="navbarExpanded = false" />
    </nuc-navbar-drawer>
  </nav>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed } from 'vue'

import {
  DOC_CATEGORIES,
  NucDocumentationNavbarNav,
  NucNavbarDrawer,
  NucNavbarLinks,
  useNavbar,
} from 'nucleify'

const route = useRoute()
const lang = computed(() => (route.params.lang as string) || 'en')
const isDevPage = computed(
  () => route.path.includes('/dev') || route.path.includes('/docs')
)
const isDocsPage = computed(() => route.path.includes('/docs'))
const { navbarExpanded, toggleNavbar } = useNavbar()
</script>

<style lang="scss">
@import 'index';
</style>
